export const selectIsRoomHost = (state) => state.isRoomHost;
export const selectConnectOnlyWithAudio = (state) => state.connectOnlyWithAudio;
export const selectRoomId = (state) => state.roomId;
export const selectIdentity = (state) => state.identity;
export const selectShowOverlay = (state) => state.showOverlay;
export const selectParticipants = (state) => state.participants;
export const selectSocketId = (state) => state.socketId;
export const selectActiveConversation = (state) => state.activeConversation;
export const selectDirectChatHistory = (state) => state.directChatHistory;
